import type { Metadata, Viewport } from 'next';
import './globals.css';
import { pathwayExtreme, oswald } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`bg-[#1C1F28] text-white ${pathwayExtreme.variable} ${oswald.variable} font-[family-name:--font-pathway-extreme] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
